# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.8
    - nodejs_version: 0.11

# combinations having this can fail
matrix:
  allow_failures:
    - nodejs_version: 0.11

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g grunt-cli
  - npm install
  - npm uninstall grunt

build: off
  
test_script:
  - node --version
  - npm --version
  - ps: grunt test --no-color # PowerShell
  - cmd: grunt test --no-color
